# Generated by Django 4.1.4 on 2023-01-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quiztag_quizchoice_quiz_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='tags',
            field=models.ManyToManyField(blank=True, through='quiz.QuizTag', to='quiz.tag'),
        ),
    ]
