# Generated by Django 4.1.4 on 2023-01-21 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_quizanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAnswerChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.TextField()),
                ('is_answer', models.BooleanField(default=False)),
                ('is_select', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer_id', models.ForeignKey(db_column='answer_id', on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='quiz.quizanswer')),
            ],
            options={
                'db_table': 'quiz_answer_choices',
            },
        ),
        migrations.AlterField(
            model_name='quiz',
            name='tags',
            field=models.ManyToManyField(blank=True, to='quiz.tag'),
        ),
        migrations.DeleteModel(
            name='QuizTag',
        ),
    ]
